name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    types:
      - completed
    branches:
      - main
    workflows:
      - 'Lucky App CI'

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
